version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: job_radar_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: jobradar
      POSTGRES_PASSWORD: jobradar
      POSTGRES_DB: job_radar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: job_radar_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
